---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  chartRef:
    kind: OCIRepository
    name: jellyfin
  interval: 1h
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.6
            env:
              TZ: America/Denver
              JELLYFIN_PublishedServerUrl: "https://jellyfin.kadenzobel.com"
            # Privileged is required to initialize the GPU driver on immutable OSs
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 4Gi

    defaultPodOptions:
      hostIPC: true # Required for Intel QuickSync memory mapping
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        supplementalGroups: [44, 104, 107, 109, 10000]

    service:
      app:
        controller: jellyfin
        ports:
          http:
            port: 8096

    route:
      app:
        enabled: true
        hostnames:
          - "jellyfin.kadenzobel.com"
        parentRefs:
          - name: envoy-external
            namespace: network

    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /config

      media:
        type: nfs
        server: 192.168.8.120
        path: /thegoodstuff
        globalMounts:
          - path: /media
            readOnly: true

      transcode-device:
        type: hostPath
        hostPath: /dev/dri/renderD128
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/dri/renderD128