apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:u2ezlT6RRWcexsc1km255I8Mloos3ByPp/g4LZs2CFaJLUdpzPYFTw==,iv:aRuvlyiXA4nU4hcIipZy2xFU3rpmWteP1jGHKZzkYag=,tag://k5Y2NFE+83DQ8avcDkDA==,type:str]
sops:
  age:
    - recipient: age10qzdgk45ngt2nqv4lc55qv6gl2a9sf9p8w5zzxm5ytw03ylwksksu3zuvn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSUFPOWYzU1BGUEdNK3J2
        WDVHOUJIRHJjWnJpbjJRN2pQVGNOdVlzLzBnCkk3dktSZENmajM5YzdEeGtMY0FJ
        Y0NvZDIvQVBZVDFIR3dtSDY4Q0xxMTgKLS0tIHoreXFPSDRmTEdOTjJOUEdZMGlB
        SzYyTnFYUnNQZ0FTT2Jzb24xMW5jUkEKrrvPPvfisJzvhxRHLcPQpI7eG6SGKOSB
        w6omq7x1xqCwfjdXDl6zDiUhJ4D5g06kjAMSIqz1udDGHBM+Le6Y9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-01T03:12:46Z"
  mac: ENC[AES256_GCM,data:tDOgKqU6j8IRq/xMK/ak2UicKxpv0gocLpB5jCIkZCnTFf9YpeLVawrMY36EsMG8bD0G0YUyoMu+qQwMoZCMiJUdayRqCjmzzGmzX/lgPHn+uOY8mkFDDaNYzwnEqGdztNR/yRJ9OaZUlqO/gOCWVmq7BVt5Vs09rD4S9tN6WCc=,iv:9zADwAYeUq48fXBVFFoK9v7royNNf+AD1SNhQsH5MPI=,tag:WE9h+UjytvJ4ZOd4YV7qOg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
