apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:5H+lx+CadNcPLVL0cQU=,iv:59EV5wBF9XJX8OqbxDmP5uFpDuMpyqSvtc6RcMGYqtM=,tag:WhlfmCM5fuzGHxcHRStDsw==,type:str]
sops:
  age:
    - recipient: age10qzdgk45ngt2nqv4lc55qv6gl2a9sf9p8w5zzxm5ytw03ylwksksu3zuvn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOFZQMEZCalk3V0M2d292
        ZDdRT0IyeFcycTBxWGR5emR5WkhmM3I5WGdRClNWVm5VUVl5dUEzZ2QvMm5XbVVH
        UktRMHM4K2RpVnFVOWtVeGpnQlVvRkEKLS0tIG1YNkxaOURMZ0djMkFXU2pWekgr
        NkI2eWFWVnRKZ25reGw4bDZJUzVjbk0KQiXUS9iU9JZjlqCitQE/dE9hn7ADV7B/
        Oas20g0VhE5T8jVcpEhGMvNigq7s434P5mcySnDgZSFVnVwXH1zWeg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-01T03:12:46Z"
  mac: ENC[AES256_GCM,data:dEiUuqqnbqI35R9mNIONIsCWri29onJqMzLcd+alUssEDrdqigEuLyqTrnU6+P76U5RPbZSUkuwHjgB/XVglZhoFS7fgjjmoqymajrBZM7cOGygwi7zcsAjM/j7a/+SN00TusTYw9EdnVjTu3ojDKNgzDb19L+9QF4gmtI51Wpc=,iv:50Y1Egrw02nsUxj7NJ2MYVPt7u2CPXq7y3GteCUdTcs=,tag:B16eGAGX7gK9TmELk1nfHg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
