apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:3DIOR1VFIq/gDQFehYoEXlGcwhIhTiXWQosSpaM6X7o=,iv:SV+EM0TarM6QU5d/g261Z5i8y5KXy373pigTQ12ooB4=,tag:InypxL1x5Yc3W4wiq7aiuw==,type:str]
sops:
  age:
    - recipient: age10qzdgk45ngt2nqv4lc55qv6gl2a9sf9p8w5zzxm5ytw03ylwksksu3zuvn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiU1RBaEVTRmoxdWpQTEZM
        a3VuQXR5S2RvQjAwWHE1b1RHR0pCRVRUdWk0CjY2ZGNqeDBHZDdsRklLTE5scTNa
        SCtlVW9hSWlOYXloZ3k5UXh2S3d6UUEKLS0tIHJxRWhiTkZtRDlzTUxLeHBPSU5q
        RUhTZWpBcDBqdDJQdVVmSmx5ZWVLVmcKzaNmWc+pdVcnDYytlFPg/CYiXIQ724M6
        QjhxVUDMr9KMDqDCtXgks04lQVXZXEak6mt3mnKdQObfcCMn/CMQhg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-01T03:12:46Z"
  mac: ENC[AES256_GCM,data:XRy6uutDK1E9HBOHqXigJEzibVAEcFrGx58ix/2CJ1iElX//HGykaxGLVOSsQiFItdJsIV3tpbG20FEA09xBD/usN5NxOwAbOq1RP4yWQB6Pnc4YqGFRmD5usHugyICOKr/5dCnp/DUjupNiESIAGXCPQcC5LxOUMH9FpH95NVc=,iv:7Ky3HmyOBe07B3eCCsgYH+I/66kiHNeLkcuGZJo68ik=,tag:dLifmIInKaeoFmA+lg5QxA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
