---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: filebrowser
  namespace: default
spec:
  interval: 12h
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
  ref:
    tag: 4.6.2
