apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:LcrfBrOHSa2236FQ7g37PIhi063NmisIwaZlr7YWloBxT41vuJRTDN99audw8ke6orYM+aWAjxhGWfgoHVIC6KV7n1UhU0klT0EnB3DtQjmxyK50tbWqC6+QpJjJL/5jYW/QEDAYNSYM0qULhPki849e3BfJvALV1HBhOH0cyLm/pSyQdkSmLvpEzsX/kfgVxBBd2B5eVp/vlkMEc/88XHRaTwqRyQCGdnf7Hn6EXN91bdpO,iv:o8QF14qge5eP1w4iG/7UVkLWKRmbtAUnndEcCtegd4k=,tag:i7smnqWlJ87eE738LXM9oA==,type:str]
sops:
  age:
    - recipient: age10qzdgk45ngt2nqv4lc55qv6gl2a9sf9p8w5zzxm5ytw03ylwksksu3zuvn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYjd0QTE1Umd4MXB5NExt
        Um1xY2xtU0RXT05wRzd1MCtOSWkzaWRiWVIwCkdQQjU3bnJlVE44cTFCdkhQZTVt
        TDdENFZ4V0NiYzhiR0Ntc1ZaUlNlSU0KLS0tIHU3V255ZHBKRlVJblZNY1NpYUZK
        ZGd3NUJsdk1IT0tZVHVRcmlVK1pwMTAK0s2gpXNWPfTL3K+vbMmushlsuyWIE8C/
        4cW/myU2Wth0JNIZJSuLnvS6Fe0UElqQsDacwlj9Na0TsaAEHZBoow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-01T03:12:46Z"
  mac: ENC[AES256_GCM,data:TvusozeZGNKcpX5DrUcKk7iPRWolaI1+TIq4C4zJthUqyayB3lfhxfYWaZa7V/o9rgCNLJyO54CqPBi1GxOSD2hKHKjzXWrWsicTiqaierN2u/VV47i2dTc+rrtIVkvhBGnhYeH7cGc4qYNhThKqA9scxhkp928qlPOAI4d50ek=,iv:MyxmOjrnhx7Plt8pKCJW1xyg3ljuxRecDqHeEd5QnoQ=,tag:LxJmfRP5VxrmG1/0579y6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
