apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:XmouyKUMEamfZxoKhBzR1sTI09ANULpnvabgbfmOrrpauXyJ8AYBdg==,iv:/jyUyxahkJDfQ3VNvpaG6UqubjzL44kdELrChGpz/Bg=,tag:dhnUEeOWucsQchX0rvXbuQ==,type:str]
sops:
  age:
    - recipient: age10qzdgk45ngt2nqv4lc55qv6gl2a9sf9p8w5zzxm5ytw03ylwksksu3zuvn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycVlqZ3VxNkc5LzAxYWN4
        SU1NQnlsOEZGNTcwUWJxOG93TjNtUnVIR0dJCldzb3VUZjZIN0dCWUJrQVBhc3ds
        SUxZYUhxS0dGa0U3M29xd0hWTXMyTGcKLS0tIElFSkFJZzdkaWc2MWFIQTNCbVZU
        NVVpcm0xM1A5SHpzaWhzVUJjVkNwTmcK6ue1CxZ5PwmP+CK9u1LF/oilY1Lsmi/6
        +2KWxftMf55+OOwfURFmCLGzukGQEw3oQ7kqih4hf6oEj1ekNUYPTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-01T03:12:46Z"
  mac: ENC[AES256_GCM,data:7EIsrGb9cDReePzoIcwDZuX55L98WehBVmmRe4Fua5+YnOLefqy5eJAY3j3sHnRuUhK9GczHFRg9DrB1ErVttBPGdxXeArZTK352nhgV+LMB3pGXCjo31QojjesBewrM4fgW3xPlroijMyAswbNbMoCkZpSOJO3vL973/xdiNUg=,iv:kV5VDB7DiPWayrSJ5FmtRvAhv7AfOY2wjpSk+zggKxY=,tag:H8fzA6j13r6lf5fvN3uRIw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
