apiVersion: apps/v1
kind: Deployment
metadata:
  name: romm-db
  namespace: romm
spec:
  selector:
    matchLabels:
      app: romm-db
  template:
    metadata:
      labels:
        app: romm-db
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.11
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: "romm_root_pass"
        - name: MARIADB_DATABASE
          value: "romm"
        - name: MARIADB_USER
          value: "romm_user"
        - name: MARIADB_PASSWORD
          value: "romm_pass"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: romm-db
  namespace: romm
spec:
  ports:
  - port: 3306
  selector:
    app: romm-db
