apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager/kustomization.yaml # Changed from ks.yaml
  - ./default/ks.yaml
  - ./flux-system/ks.yaml
  - ./kube-system/ks.yaml
  - ./network/kustomization.yaml
