apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager/  # <--- MUST end in a slash or just be the folder name
  - ./default/
#  - ./flux-system/
  - ./kube-system/
  - ./network/
