apiVersion: apps/v1
kind: Deployment
metadata:
  name: twenty-forty-eight
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twenty-forty-eight
  template:
    metadata:
      labels:
        app: twenty-forty-eight
    spec:
      containers:
      - name: game
        image: alexwhen/docker-2048
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: twenty-forty-eight
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: twenty-forty-eight